---
title: "Zadanie 8 - Heatmapa z clastrowaniem genów i próbek dla genów"
author: "Ksenia Kvitko"
date: "9 05 2020"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

# 1. Importowanie danych wygenerowanych przez program featureCounts na serwerze
```{r, results = 'hide', warning=FALSE, message=FALSE}
data22 <- read.csv('../source_files/counts_22.txt', sep = '\t', skip = 1)
dataERCC92 <- read.csv('../source_files/counts_ERCC92.txt', sep = '\t', skip = 1)
```

# 2. Normalizacja danych

```{r, results = 'hide', warning=FALSE, message=FALSE}
#BiocManager::install(c("DESeq2"))
library(DESeq2)

normalize <- function(data) {
  countData <- data[, 7:12]
  rownames(countData) = data$Geneid
  samples <- names(countData)
  cond_1 <- rep("cond1", 3)
  cond_2 <- rep("cond2", 3)
  condition <- factor(c(cond_1, cond_2))
  colData <- data.frame(samples = samples, condition = condition)
  dds <- DESeqDataSetFromMatrix(countData = countData, colData = colData, design = ~condition)
  
  log_data <- rlog(dds)
  normalized_data<- assay(log_data)
  normalized_data <- as.data.frame(normalized_data)
  
  return(normalized_data)
}

normalized_data22 <- normalize(data22)
normalized_ERCC99 <- normalize(dataERCC92)
```


# 3. Rozwiązanie zadania

### Przygotowanie heatmap

```{r, results = 'hide', warning=FALSE, message=FALSE}
#BiocManager::install(c("ComplexHeatmap"))
library(ComplexHeatmap)

drawHeatmap <- function(data) {
  threshold <- 10
  data <- data[
                data$X.home.bioinformatyka.s119494.BAM_indeks.BAM_FILES.HBR_1.bam > threshold | 
                data$X.home.bioinformatyka.s119494.BAM_indeks.BAM_FILES.HBR_2.bam > threshold | 
                data$X.home.bioinformatyka.s119494.BAM_indeks.BAM_FILES.HBR_3.bam > threshold | 
                data$X.home.bioinformatyka.s119494.BAM_indeks.BAM_FILES.UHR_1.bam > threshold | 
                data$X.home.bioinformatyka.s119494.BAM_indeks.BAM_FILES.UHR_2.bam > threshold | 
                data$X.home.bioinformatyka.s119494.BAM_indeks.BAM_FILES.UHR_3.bam > threshold
                , 
              ]
  renamed_data <- data
  colnames(renamed_data) <- c("HBR1","HBR2","HBR3", "UHR1", "UHR2", "UHR3")
  
  Heatmap(renamed_data , cluster_columns = FALSE,
          row_names_side = "left",
          row_dend_sid = "left",
          row_names_gp=gpar(cex = 0.8))
}
```

### Utworzenie heatmap
```{r, warning=FALSE}
drawHeatmap(normalized_data22)
drawHeatmap(normalized_ERCC99)
```